---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - group.angi.com
  resources:
  - myappresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - group.angi.com
  resources:
  - myappresources/finalizers
  verbs:
  - update
- apiGroups:
  - group.angi.com
  resources:
  - myappresources/status
  verbs:
  - get
  - patch
  - update
